### ISSUE TITLE
Start Menu

### ISSUE THREAD

**Issue by danielmeloalencar** [wnayes/bond-wm#13]
Could you implement a StarMenu that runs inside a Frame, with custom position and size?
Since a custom frame is required, I believe it is only possible to create a StartMenu if Bond-WM provides the necessary resources.

**Comment by wnayes** [comment]
This would follow the implementation of a ChildWindow sort of component as described in https://github.com/wnayes/bond-wm/issues/8#issuecomment-2067501846
I agree the window manager should provide these sorts of APIs.

**Comment by danielmeloalencar** [comment]
> This would follow the implementation of a ChildWindow sort of component as described in [#8 (comment)](https://github.com/wnayes/bond-wm/issues/8#issuecomment-2067501846) I agree the window manager should provide these sorts of APIs.

I tried, but the frame does not respect the x,y position configuration, only width and height

**Comment by wnayes** [comment]
Some progress on rendering a child window:

![image](https://github.com/user-attachments/assets/2d81f007-fecd-4d88-9ddc-eef73a246c49)

**Comment by danielmeloalencar** [comment]
Very good!
To make it perfect, all that's missing is the possibility of defining the initial position, height and width.
👏🏼👏🏼👏🏼

**Comment by wnayes** [comment]
There is some progress committed under 76427af5.

A `ChildWindow` component is exported from `@bond-wm/react` that allows rendering React content inside a separate electron BrowserWindow. A basic start menu component is also being built out that uses the `ChildWindow` as part of its implementation.

**Comment by danielmeloalencar** [comment]
Perfect. Thank you!
